### PR TITLE
test(equipment):TEMS-52 E2E equipment tests for CRUD

### PR DESCRIPTION
**Pull request by junix033101**
## Description

_Provide a description on what was changed/added/fixed in this PR_

## Checklist

_First, create a draft pull request. Then mark the PR as ready for review when all necessary checkbox items has been completed_

- [x] Reviewed own code
- [x] Commented on code that is hard to understand
- [x] Implemented tests for the feature/bugfix
- [x] All **_Required_** GitHub status checks pass
- [ ] The frontend and backend PR previews have been deployed

**Backend only**

- [ ] Added test data for new entity
- [ ] Generated the client api if there are new or deleted endpoints and/or DTOs

### CODE REVIEW

**Comment by noice-noise** [comment]
sorrymasen for the blocker due to the custom `EllipsisText` component, hoping you can implement the fix I've provided just fine in the future updates. Thanks, thanks!

**Review by noice-noise — DISMISSED** [review]
Noice 💜🚀

**Review by princhcanal — DISMISSED** [review]
looks super duper good 🚀

**Review by beefysalad — APPROVED** [review]
Looks good to me! Good Job!

**Pull request merged**
